---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namePrefix: dev-
# namespace: k8s-dependency-track

resources:
  - ../../../base/dependency-track
  - ../../../base/postgresql
  - ../../../base/traefik

patches:
  - path: patch-dependency-track-ingress.yaml
  - path: patch-traefik-deployment.yaml

secretGenerator:
  - name: dependency-track-tls
    namespace: dependency-track
    type: "kubernetes.io/tls"
    files:
      - tls.crt=dependency-track.localhost+1.pem
      - tls.key=dependency-track.localhost+1-key.pem
generatorOptions:
  disableNameSuffixHash: true
