hostNetwork: true
service:
  type: ClusterIP
# EntryPoints are pre-configured by the chart; enable HTTP→HTTPS redirect:
deployment:
  additionalArguments:
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
    - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
ingressClass:
  isDefaultClass: true
logs:
  general:
    level: DEBUG
