---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-frontend
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: dependency-track-frontend
        env:
        - name: API_BASE_URL
          value: "http://localhost:30081"

---
apiVersion: v1
kind: Service
metadata:
  name: dependency-track-frontend
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
