deployment:
  enabled: true

service:
  type: NodePort
  ports:
    web:
      port: 80
      nodePort: 30080
    websecure:
      port: 443
      nodePort: 30443

# Disable SSL for local development
additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--serversTransport.insecureSkipVerify=true"
  - "--api.insecure=true"
