---
service:
  type: LoadBalancer

ingressClass:
  name: traefik
  enabled: true
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: false

logs:
  general:
    level: INFO

# FIXME In `render/` directory the Traefik feature `additionalArguments` is not rendered
# additionalArguments:
#   - --entryPoints.web.address=:80
#   - --entryPoints.websecure.address=:443
#   - --entryPoints.web.http.redirections.entryPoint.to=websecure
#   - --entryPoints.web.http.redirections.entryPoint.scheme=https
