apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: dependency-track
    version: 0.34.0
    releaseName: dependency-track
    namespace: dependency-track

# resources:
#   - common-labels.yaml
