services:
  k3s-server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    hostname: k3s-server
    command: server --cluster-init --disable traefik
    privileged: true
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      K3S_TOKEN: "${K3S_TOKEN:-secure}"
      K3S_KUBECONFIG_OUTPUT: "${K3S_KUBECONFIG_OUTPUT:-/output/kubeconfig.yaml}"
      K3S_KUBECONFIG_MODE: "${K3S_KUBECONFIG_MODE:-666}"
    volumes:
      - k3s-server-data:/var/lib/rancher/k3s
      - ./config:/output
    ports:
      - "6443:6443" # Kubernetes API server
      - "80:80"     # Ingress controller HTTP
      - "443:443"   # Ingress controller HTTPS
    networks:
      - k3s-network
    restart: unless-stopped

  k3s-agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    hostname: k3s-agent
    command: agent
    privileged: true
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      K3S_URL: https://k3s-server:6443
      K3S_TOKEN: "${K3S_TOKEN:-secure}"
    depends_on:
      - k3s-server
    networks:
      - k3s-network

volumes:
  k3s-server-data:

networks:
  k3s-network:
    driver: bridge
