services:
  k3s-server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    hostname: k3s-server
    container_name: k3s-server
    command:
      - server
      # - --cluster-init
      - --disable servicelb
      - --disable traefik
    privileged: true
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      K3S_TOKEN: "${K3S_TOKEN:-secure}"
      K3S_KUBECONFIG_OUTPUT: "${K3S_KUBECONFIG_OUTPUT:-/output/kubeconfig.yaml}"
      K3S_KUBECONFIG_MODE: "${K3S_KUBECONFIG_MODE:-666}"
    volumes:
      - k3s-server-data:/var/lib/rancher/k3s
      - ./config:/output
    ports:
      - "6443:6443" # Kubernetes API server
      - "80:80" # Optional: For ingress controller HTTP (if used)
      - "443:443" # Optional: For ingress controller HTTPS (if used)
      - "30080:30080" # Dependency-Track Frontend NodePort
      - "30081:30081" # Dependency-Track API NodePort
    networks:
      - k3s-network

  k3s-agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    hostname: k3s-agent
    command:
      - agent
    privileged: true
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      K3S_URL: https://k3s-server:6443
      K3S_TOKEN: "${K3S_TOKEN:-secure}"
    depends_on:
      - k3s-server
    networks:
      - k3s-network

volumes:
  k3s-server-data:

networks:
  k3s-network:
    driver: bridge
