---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgresql

resources:
  - namespace.yaml

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: postgresql
    version: 16.7.21
    releaseName: postgresql
    namespace: postgresql
    valuesFile: values.yaml
