---
global:
  postgresql:
    auth:
      postgresPassword: longpassword
      username: dtrack
      password: dtrack
      database: dtrack

primary:
  resourcesPreset: "small"
  service:
    type: ClusterIP

tls:
  enabled: false
